devices:

    donor:
        Elite11:
            port: COM11
            diameter: 4.6 mm
            syringe_volume: 1 ml
            address: 0

    activator:
        Elite11:
            port: COM11
            diameter: 4.6 mm
            syringe_volume: 1 ml
            address: 1

    quencher:
        AzuraCompactPump:
#            mac_address: 00:80:A3:BA:C3:4A
            ip_address: 192.168.10.113
            max_pressure: 13 bar

    sample_loop:
        ViciValco:
            port: COM13
            address: 0

    chiller:
        HuberChiller:
            port: COM1

    mixer1:
        TMixer:

    mixer2:
        TMixer:


connections:
    - Tube:
        from:
            device: donor
        to:
            device: mixer1

        length: 0.1 m
        inner-diameter: 0.760 mm
        outer-diameter: 1.6 mm
        material: "PFA"

    - Tube:
        from:
            device: activator
        to:
            device: mixer1

        length: 0.1 m
        inner-diameter: 0.760 mm
        outer-diameter: 1.6 mm
        material: "PFA"

    - Interface:
          from:
              device: chiller

          betweeen:
              before: mixer1
              after: mixer2

    - Tube:
        from:
            device: mixer1
        to:
            device: mixer2

        length: 0.1 m
        inner-diameter: 0.760 mm
        outer-diameter: 1.6 mm
        material: "glass"

    - Tube:
          from:
              device: quencher
          to:
              device: mixer2

          length: 0.1 m
          inner-diameter: 0.760 mm
          outer-diameter: 1.6 mm
          material: "PFA"

    - Tube:
          from:
              device: mixer2
          to:
              device: sample_loop

          length: 0.1 m
          inner-diameter: 0.760 mm
          outer-diameter: 1.6 mm
          material: "PFA"


