devices:

    donor:
        HarvardApparatusElite11:
            port: COM11
            syringe_diameter: 14.567 mm
            syringe_volume: 10 ml
            address: 0

    activator:
        HarvardApparatusElite11:
            port: COM11
            syringe_diameter: 14.567 mm
            syringe_volume: 10 ml
            address: 1

    quencher:
        KnauerAzuraPump:
            ip_address: 192.168.10.113

    sample_loop:
        ViciValve:
            serial_port: COM13
            mapping:
                reactor: 1
                HPLC: 2

    chiller:
        HuberChiller:
            serial_port: COM1

    donor_solution:
        FlowchemVessel:
            description: Long description of the donor

connections:
    Tube:
        from:
            device: pump1
            position: 0
        to:
            device: myreagent
            position: 0

        length: 0.1 m
        inner-diameter: 0.760 mm
        outer-diameter: 1.6 mm
        material: "PFA"